name: deploy
on:
  push:
    branches:
      - main
    paths:
      - 'html/**'
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Make archive
        run: tar -czf html.tar.gz html

      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          USER: ${{ secrets.USER }}
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}
          scp: |
            ./html.tar.gz => /home/${{ secrets.USER }}
          last_ssh: |
            sudo mv /home/${{ secrets.USER }}/html.tar.gz ${{ secrets.PROJECT_PATH }}
            cd ${{ secrets.PROJECT_PATH }}
            sudo tar -xzf html.tar.gz
            sudo chown -R www-data:www-data ${{ secrets.PROJECT_PATH }}
            sudo find ${{ secrets.PROJECT_PATH }} -type d -exec chmod 775 {} +
            sudo find ${{ secrets.PROJECT_PATH }} -type f -exec chmod 664 {} +
            sudo rm html.tar.gz
