name: deploy
on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy code
      - run: sudo rsync -u -r --delete --force `pwd`/html/ ${{ secrets.PROJECT_PATH }}
      - run: sudo chown -R ${{ secrets.PROJECT_OWNER }}:${{ secrets.PROJECT_OWNER }} ${{ secrets.PROJECT_PATH }}
      - run: sudo find ${{ secrets.PROJECT_PATH }} -type d -exec chmod 775 {} +
      - run: sudo find ${{ secrets.PROJECT_PATH }} -type f -exec chmod 664 {} +
